In [31]:
from marcap import marcap_data
df = marcap_data('2023-08-21')

In [18]:
df

,Code,Name,Close,Dept,ChangeCode,Changes,ChagesRatio,Volume,Amount,Open,High,Low,Marcap,Stocks,Market,MarketId,Rank
Date,,,,,,,,,,,,,,,,,
2023-08-21,005930,삼성전자,66600,NaN,1,300,0.45,9720067,647498994572,66600,67100,66300,397587517830000,5969782550,KOSPI,STK,1
2023-08-21,373220,LG에너지솔루션,526000,NaN,2,-3000,-0.57,251626,132693989000,530000,534000,522000,123084000000000,234000000,KOSPI,STK,2
2023-08-21,000660,SK하이닉스,116400,NaN,2,-800,-0.68,2621973,305368985600,117300,118500,115600,84739475286000,728002365,KOSPI,STK,3
2023-08-21,207940,삼성바이오로직스,778000,NaN,1,7000,0.91,31231,24329466000,771000,789000,770000,55373372000000,71174000,KOSPI,STK,4
2023-08-21,005490,POSCO홀딩스,551000,NaN,1,2000,0.36,950697,526139630000,549000,563000,545000,46598747730000,84571230,KOSPI,STK,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-21,001527,동양2우B,10300,NaN,1,200,1.98,1249,12845010,10300,10380,10110,3178260700,308569,KOSPI,STK,2741
2023-08-21,245450,씨앤에스링크,1701,일반기업부,1,1,0.06,31,52799,1799,1799,1600,2687511960,1579960,KONEX,KNX,2743
2023-08-21,288490,나라소프트,56,일반기업부,2,-6,-9.68,865615,46797671,65,65,53,2422952280,43267005,KONEX,KNX,2744
2023-08-21,322190,베른,170,일반기업부,3,0,0.00,63,9549,194,194,145,1517283490,8925197,KONEX,KNX,2745
2023-08-21,308700,테크엔,200,일반기업부,2,-32,-13.79,444,117204,266,266,200,800000000,4000000,KONEX,KNX,2746

In [19]:
df.loc[df['Name'] == "LG디스플레이", 'Marcap'].values[0]

4773261438000

In [32]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

# 주어진 데이터 프레임을 생성 (이 예시에서는 임의의 데이터로 생성)
df = df[df['Name'] != '삼성전자']
# df = df[df['Name'] != 'LG에너지솔루션']
# 스케일러 생성 및 적용
scaler = MinMaxScaler(feature_range=(300, 10000))
df['Marcap_scaled'] = scaler.fit_transform(df[['Marcap']])

print(df)

              Code      Name   Close   Dept ChangeCode  Changes  ChagesRatio  \
Date
2023-08-21  373220  LG에너지솔루션  526000    NaN          2    -3000        -0.57
2023-08-21  000660    SK하이닉스  116400    NaN          2     -800        -0.68
2023-08-21  207940  삼성바이오로직스  778000    NaN          1     7000         0.91
2023-08-21  005490  POSCO홀딩스  551000    NaN          1     2000         0.36
2023-08-21  005935     삼성전자우   54300    NaN          2     -200        -0.37
...            ...       ...     ...    ...        ...      ...          ...
2023-08-21  001527     동양2우B   10300    NaN          1      200         1.98
2023-08-21  245450    씨앤에스링크    1701  일반기업부          1        1         0.06
2023-08-21  288490     나라소프트      56  일반기업부          2       -6        -9.68
2023-08-21  322190        베른     170  일반기업부          3        0         0.00
2023-08-21  308700       테크엔     200  일반기업부          2      -32       -13.79

             Volume        Amount    Open    High     Low           Marcap  \
Date
2023-08-21   251626  132693989000  530000  534000  522000  123084000000000
2023-08-21  2621973  305368985600  117300  118500  115600   84739475286000
2023-08-21    31231   24329466000  771000  789000  770000   55373372000000
2023-08-21   950697  526139630000  549000  563000  545000   46598747730000
2023-08-21   638880   34813521400   54500   55000   54200   44682747810000
...             ...           ...     ...     ...     ...              ...
2023-08-21     1249      12845010   10300   10380   10110       3178260700
2023-08-21       31         52799    1799    1799    1600       2687511960
2023-08-21   865615      46797671      65      65      53       2422952280
2023-08-21       63          9549     194     194     145       1517283490
2023-08-21      444        117204     266     266     200        800000000

               Stocks Market MarketId  Rank  Marcap_scaled
Date
2023-08-21  234000000  KOSPI      STK     2   10000.000000
2023-08-21  728002365  KOSPI      STK     3    6978.126262
2023-08-21   71174000  KOSPI      STK     4    4663.828276
2023-08-21   84571230  KOSPI      STK     5    3972.313467
2023-08-21  822886700  KOSPI      STK     6    3821.316425
...               ...    ...      ...   ...            ...
2023-08-21     308569  KOSPI      STK  2741     300.187427
2023-08-21    1579960  KONEX      KNX  2743     300.148752
2023-08-21   43267005  KONEX      KNX  2744     300.127902
2023-08-21    8925197  KONEX      KNX  2745     300.056528
2023-08-21    4000000  KONEX      KNX  2746     300.000000

[2630 rows x 18 columns]

In [33]:
# 'Name', 'Marcap', 'Marcap_scaled' 열만 선택하여 새로운 데이터프레임 생성
selected_df = df[['Name', 'Marcap', 'Marcap_scaled']]

# CSV 파일로 저장
selected_df.to_csv('시총_스케일러_re.csv', index=False)